extends LevelBase

# Level built from trenchbroom/maps/level_02.map (generated by tools/levelgen/make_level_02.py).
# The map is built when the level starts (see rebuild_at_runtime) and the navigation mesh is baked here so
# enemies can path. Press Build on the FuncGodotMap in the editor only if you want to preview it in the editor.

@onready var map: FuncGodotMap = $NavigationRegion3D/FuncGodotMap
@onready var navigation: NavigationRegion3D = $NavigationRegion3D
@onready var player: Node3D = $Player


# Build the level from the .map file every time the game starts, throwing away anything baked into the scene.
# Saving in TrenchBroom and pressing play is then enough; no need to press Build first.
@export var rebuild_at_runtime := true


func _ready() -> void:
	if rebuild_at_runtime:
		for child in map.get_children():
			map.remove_child(child)
			child.queue_free()
	if map.get_child_count() == 0:
		await _build_map()
	ensure_world_collision(map)
	_move_player_to_start()
	# Always bake fresh so the nav mesh matches the current map (a mesh saved in the scene can go stale)
	_bake_navigation()


# Builds the map and waits until every step has finished
func _build_map() -> void:
	var finished := [false]
	map.build_complete.connect(func(): finished[0] = true, CONNECT_ONE_SHOT)
	map.block_until_complete = true
	map.verify_and_build()
	while not finished[0]:
		await get_tree().process_frame


# Bakes the nav mesh from the level's static colliders (enemies and pickups are ignored)
func _bake_navigation() -> void:
	navigation.bake_navigation_mesh(false)
	if navigation.navigation_mesh.get_polygon_count() == 0:
		push_warning("Level 02: navigation bake produced no polygons")


# Puts the player on the info_player_start entity and turns them to face its angle
func _move_player_to_start() -> void:
	var start := _find_entity("info_player_start")
	if start == null:
		return
	player.global_position = start.global_position + Vector3(0, 0.1, 0)
	player.global_rotation.y = start.global_rotation.y


func _find_entity(classname: String) -> Node3D:
	for node in map.find_children("entity_*_" + classname, "Node3D", true, false):
		return node as Node3D
	return null
