extends Node3D

# Small test arena built from trenchbroom/maps/level_02.map (generated by tools/levelgen/make_level_02.py).
# Press Build on the FuncGodotMap in the editor to bake the map into this scene. If the map has not been
# baked yet, it is built when the level starts so the scene still runs.

@onready var map: FuncGodotMap = $NavigationRegion3D/FuncGodotMap
@onready var navigation: NavigationRegion3D = $NavigationRegion3D
@onready var player: Node3D = $Player


func _ready() -> void:
	if map.get_child_count() == 0:
		map.block_until_complete = true
		map.verify_and_build()
		navigation.bake_navigation_mesh(false)
	_move_player_to_start()


# Puts the player on the info_player_start entity and turns them to face its angle
func _move_player_to_start() -> void:
	var start := _find_entity("info_player_start")
	if start == null:
		return
	player.global_position = start.global_position + Vector3(0, 0.1, 0)
	player.global_rotation.y = start.global_rotation.y


func _find_entity(classname: String) -> Node3D:
	for node in map.find_children("entity_*_" + classname, "Node3D", true, false):
		return node as Node3D
	return null
